name: "teller"

version: "0.1.0"
usage: "Helm Teller plugin"
description: "Helm Teller plugin allows you to pull any values from the supported provider into your helm chart"

command: "$HELM_PLUGIN_DIR/bin/teller"
hooks:
  install: "cd $HELM_PLUGIN_DIR/scripts/install.sh"
  update: "cd $HELM_PLUGIN_DIR/scripts/install.sh"
