name: Release
on:
  push:
    tags:
    - 'v*.*.*'
    - 'v*.*.*-rc*'
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: v1.5.0
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
